### ISSUE TITLE
Documenting styling

### ISSUE THREAD

**Issue by brettz9** [ericcornelissen/pinned-tabs-for-atom#42]
Given especially that certain themes (in my case, the UI Dark theme) may reduce the prominence of pinned tabs too much to the extent that they become harder to find to click on, I thought it could be useful for you to make mention in your docs (if not settings as well) of how pinned tabs can be targeted within `Atom->Stylesheet...` (`~/.atom/styles.less`).

As I detailed at https://github.com/averrin/color-tabs-regex/issues/18 , a user could target them (based on active/inactive state) such as follows:

```css
    .tab.pinned.active[data-type$="Editor"] {
        background-image: none;
        background-color: white;
    }
    .tab.pinned:not(.active)[data-type$="Editor"] {
        border-radius: 10px;
        border-top: 1px solid white;
        border-bottom: 1px solid white;
        border-right: 1px outset white;
        border-left: 1px outset white;
        opacity: 0.7;
    }
```

And FWIW, at that link, I also mention how to target tabs with specific file types, something that could also be applied to pinned tabs of a specific file type/extension if one wished.

**Comment by ericcornelissen** [comment]
Thanks for the suggestion, great idea 👍

I did a quick draft below, let me know what you think @brettz9 (I specifically left out `[data-type$="Editor"]` because it is also possible to pin for example the settings tab...)

* * *

# Customization

You can add custom styles for pinned tabs. Use your [Stylesheet](https://flight-manual.atom.io/using-atom/sections/basic-customization/#style-tweaks) and target `.tab.pinned` to tweak a pinned tab. You can consult the [package stylesheet](./styles/pinned-tabs.less) to see what classes are used.

Below are a few examples of ways to customize the styling of pinned tabs.

### Style the active pinned tab specifically
```css
.tab.pinned.active {
    ...
}

/* Or all not active pinned tabs */
.tab.pinned:not(.active) {
    ...
}
```

### Change the icon
```css
.tab.pinned > .title::before {
     /* The icon size */
    font-size: medium; 18px;

    /* The icon itself */
    font-family: Devicons;
    content: "\E64E";
}
```

If you're using File Icon, you can check out its [customization documentation](https://github.com/file-icons/atom#customisation) as well.

### Change the icon of a modified tab
```css
.tab.pinned.modified:hover .title::before {
    border: none; /* The default is produced with a border */
    font-size: 18px;
    font-family: Devicons;
    content: "\E64E";
}
```

### Change the pinned icon (when using visual studio pinning)
```css
.tab.pinned .close-icon::before {
    font-family: Devicons;
    content: "\E64E";
}
```
